export default {
	login               : "lawrenceagles",
	id                  : 9684204,
	node_id             : "MDQ6VXNlcjk2ODQyMDQ=",
	avatar_url          : "https://avatars2.githubusercontent.com/u/9684204?v=4",
	gravatar_id         : "",
	url                 : "https://api.github.com/users/lawrenceagles",
	html_url            : "https://github.com/lawrenceagles",
	followers_url       : "https://api.github.com/users/lawrenceagles/followers",
	following_url       : "https://api.github.com/users/lawrenceagles/following{/other_user}",
	gists_url           : "https://api.github.com/users/lawrenceagles/gists{/gist_id}",
	starred_url         : "https://api.github.com/users/lawrenceagles/starred{/owner}{/repo}",
	subscriptions_url   : "https://api.github.com/users/lawrenceagles/subscriptions",
	organizations_url   : "https://api.github.com/users/lawrenceagles/orgs",
	repos_url           : "https://api.github.com/users/lawrenceagles/repos",
	events_url          : "https://api.github.com/users/lawrenceagles/events{/privacy}",
	received_events_url : "https://api.github.com/users/lawrenceagles/received_events",
	type                : "User",
	site_admin          : false,
	name                : "Lawrence Eagles",
	company             : null,
	blog                : "",
	location            : "Nigeria",
	email               : null,
	hireable            : true,
	bio                 :
		"I’m a full-stack Javascript developer, a Linux lover and a passionate tutor. I bring a strong blend of creativity & simplicity…",
	twitter_username    : null,
	public_repos        : 16,
	public_gists        : 29,
	followers           : 7,
	following           : 6,
	created_at          : "2014-11-11T22:38:23Z",
	updated_at          : "2020-08-01T18:57:19Z",
};
