export default [
	{
		login               : "newfotune",
		id                  : 16793240,
		node_id             : "MDQ6VXNlcjE2NzkzMjQw",
		avatar_url          : "https://avatars2.githubusercontent.com/u/16793240?v=4",
		gravatar_id         : "",
		url                 : "https://api.github.com/users/newfotune",
		html_url            : "https://github.com/newfotune",
		followers_url       : "https://api.github.com/users/newfotune/followers",
		following_url       : "https://api.github.com/users/newfotune/following{/other_user}",
		gists_url           : "https://api.github.com/users/newfotune/gists{/gist_id}",
		starred_url         : "https://api.github.com/users/newfotune/starred{/owner}{/repo}",
		subscriptions_url   : "https://api.github.com/users/newfotune/subscriptions",
		organizations_url   : "https://api.github.com/users/newfotune/orgs",
		repos_url           : "https://api.github.com/users/newfotune/repos",
		events_url          : "https://api.github.com/users/newfotune/events{/privacy}",
		received_events_url : "https://api.github.com/users/newfotune/received_events",
		type                : "User",
		site_admin          : false,
	},
	{
		login               : "nelsonic",
		id                  : 194400,
		node_id             : "MDQ6VXNlcjE5NDQwMA==",
		avatar_url          : "https://avatars3.githubusercontent.com/u/194400?v=4",
		gravatar_id         : "",
		url                 : "https://api.github.com/users/nelsonic",
		html_url            : "https://github.com/nelsonic",
		followers_url       : "https://api.github.com/users/nelsonic/followers",
		following_url       : "https://api.github.com/users/nelsonic/following{/other_user}",
		gists_url           : "https://api.github.com/users/nelsonic/gists{/gist_id}",
		starred_url         : "https://api.github.com/users/nelsonic/starred{/owner}{/repo}",
		subscriptions_url   : "https://api.github.com/users/nelsonic/subscriptions",
		organizations_url   : "https://api.github.com/users/nelsonic/orgs",
		repos_url           : "https://api.github.com/users/nelsonic/repos",
		events_url          : "https://api.github.com/users/nelsonic/events{/privacy}",
		received_events_url : "https://api.github.com/users/nelsonic/received_events",
		type                : "User",
		site_admin          : false,
	},
	{
		login               : "jessuppi",
		id                  : 17551083,
		node_id             : "MDQ6VXNlcjE3NTUxMDgz",
		avatar_url          : "https://avatars0.githubusercontent.com/u/17551083?v=4",
		gravatar_id         : "",
		url                 : "https://api.github.com/users/jessuppi",
		html_url            : "https://github.com/jessuppi",
		followers_url       : "https://api.github.com/users/jessuppi/followers",
		following_url       : "https://api.github.com/users/jessuppi/following{/other_user}",
		gists_url           : "https://api.github.com/users/jessuppi/gists{/gist_id}",
		starred_url         : "https://api.github.com/users/jessuppi/starred{/owner}{/repo}",
		subscriptions_url   : "https://api.github.com/users/jessuppi/subscriptions",
		organizations_url   : "https://api.github.com/users/jessuppi/orgs",
		repos_url           : "https://api.github.com/users/jessuppi/repos",
		events_url          : "https://api.github.com/users/jessuppi/events{/privacy}",
		received_events_url : "https://api.github.com/users/jessuppi/received_events",
		type                : "User",
		site_admin          : false,
	},
	{
		login               : "batermj",
		id                  : 250445,
		node_id             : "MDQ6VXNlcjI1MDQ0NQ==",
		avatar_url          : "https://avatars0.githubusercontent.com/u/250445?v=4",
		gravatar_id         : "",
		url                 : "https://api.github.com/users/batermj",
		html_url            : "https://github.com/batermj",
		followers_url       : "https://api.github.com/users/batermj/followers",
		following_url       : "https://api.github.com/users/batermj/following{/other_user}",
		gists_url           : "https://api.github.com/users/batermj/gists{/gist_id}",
		starred_url         : "https://api.github.com/users/batermj/starred{/owner}{/repo}",
		subscriptions_url   : "https://api.github.com/users/batermj/subscriptions",
		organizations_url   : "https://api.github.com/users/batermj/orgs",
		repos_url           : "https://api.github.com/users/batermj/repos",
		events_url          : "https://api.github.com/users/batermj/events{/privacy}",
		received_events_url : "https://api.github.com/users/batermj/received_events",
		type                : "User",
		site_admin          : false,
	},
	{
		login               : "ChukwurahVictor",
		id                  : 31727181,
		node_id             : "MDQ6VXNlcjMxNzI3MTgx",
		avatar_url          : "https://avatars3.githubusercontent.com/u/31727181?v=4",
		gravatar_id         : "",
		url                 : "https://api.github.com/users/ChukwurahVictor",
		html_url            : "https://github.com/ChukwurahVictor",
		followers_url       : "https://api.github.com/users/ChukwurahVictor/followers",
		following_url       : "https://api.github.com/users/ChukwurahVictor/following{/other_user}",
		gists_url           : "https://api.github.com/users/ChukwurahVictor/gists{/gist_id}",
		starred_url         : "https://api.github.com/users/ChukwurahVictor/starred{/owner}{/repo}",
		subscriptions_url   : "https://api.github.com/users/ChukwurahVictor/subscriptions",
		organizations_url   : "https://api.github.com/users/ChukwurahVictor/orgs",
		repos_url           : "https://api.github.com/users/ChukwurahVictor/repos",
		events_url          : "https://api.github.com/users/ChukwurahVictor/events{/privacy}",
		received_events_url : "https://api.github.com/users/ChukwurahVictor/received_events",
		type                : "User",
		site_admin          : false,
	},
	{
		login               : "YumekaMengjiaLYU",
		id                  : 53891017,
		node_id             : "MDQ6VXNlcjUzODkxMDE3",
		avatar_url          : "https://avatars1.githubusercontent.com/u/53891017?v=4",
		gravatar_id         : "",
		url                 : "https://api.github.com/users/YumekaMengjiaLYU",
		html_url            : "https://github.com/YumekaMengjiaLYU",
		followers_url       : "https://api.github.com/users/YumekaMengjiaLYU/followers",
		following_url       : "https://api.github.com/users/YumekaMengjiaLYU/following{/other_user}",
		gists_url           : "https://api.github.com/users/YumekaMengjiaLYU/gists{/gist_id}",
		starred_url         : "https://api.github.com/users/YumekaMengjiaLYU/starred{/owner}{/repo}",
		subscriptions_url   : "https://api.github.com/users/YumekaMengjiaLYU/subscriptions",
		organizations_url   : "https://api.github.com/users/YumekaMengjiaLYU/orgs",
		repos_url           : "https://api.github.com/users/YumekaMengjiaLYU/repos",
		events_url          : "https://api.github.com/users/YumekaMengjiaLYU/events{/privacy}",
		received_events_url : "https://api.github.com/users/YumekaMengjiaLYU/received_events",
		type                : "User",
		site_admin          : false,
	},
	{
		login               : "Praizbenzy",
		id                  : 60606489,
		node_id             : "MDQ6VXNlcjYwNjA2NDg5",
		avatar_url          : "https://avatars3.githubusercontent.com/u/60606489?v=4",
		gravatar_id         : "",
		url                 : "https://api.github.com/users/Praizbenzy",
		html_url            : "https://github.com/Praizbenzy",
		followers_url       : "https://api.github.com/users/Praizbenzy/followers",
		following_url       : "https://api.github.com/users/Praizbenzy/following{/other_user}",
		gists_url           : "https://api.github.com/users/Praizbenzy/gists{/gist_id}",
		starred_url         : "https://api.github.com/users/Praizbenzy/starred{/owner}{/repo}",
		subscriptions_url   : "https://api.github.com/users/Praizbenzy/subscriptions",
		organizations_url   : "https://api.github.com/users/Praizbenzy/orgs",
		repos_url           : "https://api.github.com/users/Praizbenzy/repos",
		events_url          : "https://api.github.com/users/Praizbenzy/events{/privacy}",
		received_events_url : "https://api.github.com/users/Praizbenzy/received_events",
		type                : "User",
		site_admin          : false,
	},
];
